package com.mygdx.robotlegend;

public class ServerPacket {
    int Hid = 1;
    int Bid = 1;
    int RHid = 1;
    int LHid = 1;
    int RLid = 1;
    int LLid = 1;
    int EHid = 1;
    int EBid = 1;
    int ERHid = 1;
    int ELHid = 1;
    int ERLid = 1;
    int ELLid = 1;
 /*   float ball_state = 0.0f;
    int resize_y = 0;
    int alert_x = 400;
    int alert_y = 0;
    int alert_x_plus = 0;
    int gift_size;
    int gift_y;
    int gift_x;
    int press_y;
    int front_energy_scale = 0;
    int win_y = 0;
    int boom_x = 0;
    int boom_y = 0;
    int boom_anime = 1;
    int boom_height = 0;
    int robot_speed_bonus = 0;
    float win_rot = 0.0f;
    int win_scale = 0;
    int win = 0;
    int win_type = 0;
    int win_num = 0;
    int meteor_splash_size = 0;
    int cross_size= 0;
    int meteor_x = 0;
    int meteor_y = 0;
    int will_meteor_x = 0;
    int will_meteor_y = 0;
    int med_x = 0;
    int med_y = 0;
    int med_scale = 0;
    int med_anime = 0;
    int[] bullets_x = new int[40];
    double[] bullets_y = new double[40];
    int[] bullets_dir = new int[40];
    int[] bullets_type = new int[40];
    int warning = 0;
    int lastnumbullet;
    int bullets = 0;
    int pos_interface = 0;
    int dir = 1;
    int y = 1;
    int x = 1;
    int health;
    int grass_dir = 1;
    int energy;
    int energy_use = 0;
    int openlevel_x = 0;
    int time = 120;
    int type_achivement = 1;
    int gift_index = 0;
    int local_speed = 0;
    int resized = 0;
    double speed = 1.0;
    double anime_grass = 0;
    double rotate_planet = 0;
    double x_planet = 0;
    int[] grass_1 = new int[5];
    int[] grass_2 = new int[5];
    int[] grass_3 = new int[5];
    double scale_inteface = 1.1;
    double robot_x = 0;
    double robot_y = 0;
    float rothand = 0;
    float rotleg = 0;
    float rothead = 0;
    float rot = 0;
    float scale = 0.8f;
    float meteor_rot = 0.0f;
    boolean music_swapped = false;
    boolean ball_can = true;
    boolean ball_clicked = false;
    boolean needGift = false;
    boolean gift_swap = false;
    boolean gift_added = false;
    boolean robotboom = false;
    boolean isboom = false;
    boolean meteor_rocket = false;
    boolean med_used = false;
    boolean med_is = false;
    boolean med_swap = false;
    boolean meteor_splash = false;
    boolean meteor_run = false;
    boolean dead = false;
    boolean hurt = false;
    boolean fire_clicked = false;
    boolean swap = false;
    boolean redir_clicked = false;
    boolean up_clicked = false;
    boolean down_clicked = false;
    boolean jump_clicked = false;
    boolean end = false;
    boolean ending = false;
    boolean moreboom = false; */
    int turnedJump = 0;
    int turnedFire = 0;
    int turnedUp = 0;
    int turnedDown = 0;
    int turnedBall = 0;
    int turnedMeteor = 0;
    int turnedBoom = 0;
    int turnedRedir = 0;
}
